---
container_name: "teleop-server"
image: "shadowrobot/dexterous-hand"
tag: "kinetic-release"
ethercat_interface: "eth0"
sr_branch_name: "demohand_A"
nuc_address: "10.6.10.3"
nuc_name: "user"
user_folder: "/home/{{ user }}"
