
- name: Install Teleop software on Windows Machine
  hosts: windows_machine_group
  connection: windows_machine_group
  remote_user: shadowop
  vars_files:
    - vars/teleop-deploy.yml
  pre_tasks:
    - name: Product is not teleop, ending play
      when: product != 'teleop'
      meta: end_play

    - name: set the value for user
      set_fact:
        user: shadowop

  roles:
    - { role: installation/docker }
    - { role: products/teleop/windows-machine/deploy }