
- name: Install Teleop software on control machine 
  hosts: control_machine_group
  connection: control_machine_group
  remote_user: "user"
  vars_files:
    - vars/teleop-deploy.yml
  pre_tasks:
    - name: Product is not teleop, ending play
      when: product != 'teleop'
      meta: end_play

    - name: check if customer_key is provided and not false
      when: customer_key is defined and customer_key|bool
      set_fact:
        use_aws: true
      
    - name: check if cyberglove branch is provided
      when: cyberglove is defined and cyberglove|bool
      set_fact:
        use_cyberglove: true

    - name: set the value for user
      set_fact:
        user: "user"

    - name: Add teleop-server IP to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: '{{ ansible_default_ipv4.address }} teleop-server'
        insertbefore: EOF

  roles:
    - { role: installation/docker }
    - { role: products/teleop/control-machine/deploy }
    - { role: aws, when: use_aws }