---
- name: Prepare teleop-deploy playbook
  connection: localhost
  hosts: localhost
  vars_files:
    - vars/teleop-deploy.yml
  pre_tasks:
    - name: No teleop client IP is defined (e.g. client=10.5.10.7)
      when: client == ''
      meta: end_play

    - name: Teleop client operating system is not windows or ubuntu (e.g. client_os=ubuntu)
      when: client_os != 'windows' and client_os != 'ubuntu'
      meta: end_play

- name: Install Teleop software on this teleop server machine
  import_playbook: teleop-server.yml

- name: Install Teleop software for Ubuntu on teleop client laptop
  when: client_os == 'ubuntu'
  import_playbook: teleop-client-ubuntu.yml
  
  



