---
- name: Prepare teleop-deploy playbook
  connection: localhost
  hosts: localhost
  become: true
  vars_files:
    - vars/teleop-deploy.yml
  environment:
    ANSIBLE_HOST_KEY_CHECKING: False
  pre_tasks:
    - name: No control_machine IP is defined (e.g. control_machine=10.5.10.7)
      when: control_machine == ''
      meta: end_play

    - name: No windows_machine IP is defined (e.g. windows_machine=10.5.10.8)
      when: windows_machine == '' and use_windows
      meta: end_play

    - name: Add control_machine IP to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: '{{ control_machine }} control_machine'
        insertbefore: EOF

    - name: Add windows_machine IP to /etc/hosts
      when: use_windows
      lineinfile:
        path: /etc/hosts
        line: '{{ windows_machine }} windows_machine'
        insertbefore: EOF

- name: Install Teleop software on this teleop server machine
  import_playbook: teleop-server.yml

- name: Install Teleop software on teleop control machine
  import_playbook: control-machine.yml

- name: Install Teleop software on teleop windows machine machine
  when: use_windows
  import_playbook: windows-machine.yml
  
  