---
- name: Prepare teleop-deploy playbook
  connection: localhost
  hosts: localhost
  become: true
  vars_files:
    - vars/teleop-deploy.yml
  pre_tasks:

    - name: Add control_machine IP to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: '{{ control_machine }} control_machine'
        insertbefore: EOF

    - name: Add windows_machine IP to /etc/hosts
      when: use_windows
      lineinfile:
        path: /etc/hosts
        line: '{{ windows_machine }} windows_machine'
        insertbefore: EOF

- name: Install Teleop software on this teleop server machine
  import_playbook: teleop-server.yml

- name: Install Teleop software on teleop control machine
  import_playbook: control-machine.yml

- name: Install Teleop software on teleop windows machine machine
  when: use_windows
  import_playbook: windows-machine.yml
  
  

  teleop_server: false
teleop_client: false
control_machine: false
windows_machine: false
staging: false
production: false
ethercat_interface: "eth0"
use_aws: true
customer_key: false
nvidia_docker: false
reinstall: false
launch_hand: false
product: 'teleop'
use_windows: false
openvpn_server: false