---
- name: Create keypair for ssh
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', '/home/user/.ssh/id_rsa.pub') }}"
    state: present

- name: Copying ssh key to Control-machine
  copy:
    src: "{{ user_folder }}/.ssh"
    dest: "/home/user/.ssh/{{ item }}"
    mode: 0600
    state: present
  with_items:
    - id_rsa
    - id_rsa.pub
